from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
AUDIT = ROOT / "scripts" / "project_audit.py"
sys.path.insert(0, str(ROOT / "scripts"))


def test_audit_json_contains_current_identity() -> None:
    result = subprocess.run(
        [sys.executable, str(AUDIT), "--json"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode in (0, 1), result.stdout + result.stderr
    payload = json.loads(result.stdout)
    assert payload["head"]
    assert payload["version"] == json.loads((ROOT / "plugin.json").read_text())["version"]
    assert payload["inventory"]["test_files"] > 0
    assert "core_ok" in payload["doctor"]


def test_generated_baseline_contains_current_identity(tmp_path: Path) -> None:
    from project_audit import baseline_is_current, build_snapshot, markdown

    snapshot = build_snapshot()
    report = markdown(snapshot)
    assert f"HEAD: `{snapshot['head']}`" in report
    assert f"Source fingerprint: `{snapshot['source_fingerprint']}`" in report
    assert f"Plugin version: `{snapshot['version']}`" in report
    assert "Remaining production gates" in report
    assert "generated by `scripts/project_audit.py`" in report
    stale = tmp_path / "stale.md"
    stale.write_text("- HEAD: `old`\n- Plugin version: `0.0.0`\n", encoding="utf-8")
    assert baseline_is_current(stale) is False


def test_baseline_becomes_stale_when_source_fingerprint_changes(
    tmp_path: Path, monkeypatch
) -> None:
    import project_audit

    snapshot = project_audit.build_snapshot()
    report = tmp_path / "baseline.md"
    report.write_text(project_audit.markdown(snapshot), encoding="utf-8")
    assert project_audit.baseline_is_current(report) is True
    monkeypatch.setattr(project_audit, "source_fingerprint", lambda: "changed")
    assert project_audit.baseline_is_current(report) is False
