#!/usr/bin/env python3
"""TTS half of the dual pipeline (contract + selection + voice QA).

BGM and TTS are two parallel lanes:
  - BGM gaps are GENERATED by sound backends (acep-step/ltx/grok/h3) and run
    through qa_audio's music gates.
  - TTS gaps are NOT generated here — they are routed to an already-EVALUATED
    TTS engine (see tts-evaluations/manifest.json) and served from that
    engine's sample pool. generate_loop only ROUTES a tts gap (logs it) and
    leaves it for the tts pipeline; it never hands a tts gap to a sound backend.

This module provides:
  - gap_asset_kind(g)        default "bgm" when a gap omits asset_kind
  - choose_tts_engine()      pick an active engine with samples (or None)
  - tts_qa(path, spec)       voice-appropriate QA (reuses qa_audio hard gates,
                             but the seamless-loop check is meaningless for a
                             spoken line, so it is suppressed)
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pipeline_lib import LIB
from qa_audio import qa_asset

MANIFEST = os.path.join(LIB, "..", "tts-evaluations", "manifest.json")


def gap_asset_kind(g):
    """A gap's lane: 'tts' or 'bgm' (default)."""
    return g.get("asset_kind") or "bgm"


def load_manifest():
    if not os.path.exists(MANIFEST):
        return None
    return json.load(open(MANIFEST, encoding="utf-8"))


def choose_tts_engine(manifest=None):
    """Return (engine_id, engine_dict) for an active engine that has samples,
    preferring the one with the most evaluated samples; None if none."""
    m = manifest or load_manifest()
    if not m:
        return None
    engines = m.get("engines", {})
    cands = [(eid, e) for eid, e in engines.items()
             if e.get("status") == "active" and e.get("samples")]
    if not cands:
        return None
    cands.sort(key=lambda kv: len(kv[1].get("samples", [])), reverse=True)
    return cands[0]


def tts_qa(path, spec=None):
    """Voice QA: same hard gates as music (peak/rms/silence/duration) but the
    seamless-loop advisory is suppressed — a spoken line should not be looped.
    Returns the same shape as qa_audio.qa_asset (ok, metrics, issues,
    advisories)."""
    # loop_min=-1 guarantees the loop advisory never fires for voice
    res = qa_asset(path, spec=spec, thresholds={"loop_min": -1.0})
    res["advisories"] = [a for a in res["advisories"]
                         if not a.startswith("loop_score")]
    res["advisories"].append("tts voice asset (seamless-loop check skipped)")
    res["kind"] = "tts"
    return res


if __name__ == "__main__":
    eng = choose_tts_engine()
    print("tts engine:", eng[0] if eng else None)
